name: paddle
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  collection: ">=1.18.0 <2.0.0"
  equatable: ">=2.0.5 <3.0.0"
  json_annotation: ^4.9.0
  chopper: ^8.1.0
  http: ">=1.2.2 <2.0.0"
  logging: ^1.3.0

dev_dependencies:
  lints: ^5.1.1
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  chopper_generator: ^8.1.0

